name: dash
channels:
  - conda-forge
  - dlr-sc
dependencies:
  - python=3.9
  - pip=21.1.2
  - occt=7.5.2
  - opencascade=7.4.0
  - pythonocc-core=7.5.1
  - flask=2.0.1
  - flask-cors=3.0.10
  - python-dotenv
  - peewee=3.14.4
  - pillow=8.2.0
  - pymysql=1.0.2
  - requests=2.25.1
  - tornado=6.1
  - pip:
      - python-git-info==0.7.1
